.PHONY: test

test:
	python3 -m unittest \
		implementation.test_task_pack.SeoImplementationTaskPackTest.test_dashboard_has_exactly_16_unique_task_ids \
		implementation.test_task_pack.SeoImplementationTaskPackTest.test_every_dashboard_task_has_exactly_one_file \
		implementation.test_task_pack.SeoImplementationTaskPackTest.test_w1_03_contains_all_baseline_findings \
		-v
